### ISSUE TITLE
How do I get the value the user entered

### ISSUE THREAD

**Issue by onimisionipe** [twobucks/react-gcaptcha#1]
How do I get the value the user entered to send to my server and to google for validation.

**Comment by dinodsaurus** [comment]
You cannot do that, you get a key from google and then you need to check it on your server.

**Comment by dodekeract** [comment]
Could you add a link to some documentation on that one? It's quite hard to find out what to do, when you're only given half of the source.

**Comment by dinodsaurus** [comment]
yea, you can find all the links in the project description 👍

**Comment by stevematdavies** [comment]
This should not be closed, the question refers to the response the user gets after successfully using recaptcha BEFORE the verification is sent to GOOGLE. This request needs a response which is to what the user here is referring to. As usual, no one can seem to give a clear example.

**Comment by dinodsaurus** [comment]
Sorry but I dont understand your point here, this library does everything on frontend so no need on sending the captcha text to backend...
Here is the documentation with the APIs - https://developers.google.com/recaptcha/docs/display
