### ISSUE TITLE
Reset captcha callback

### ISSUE THREAD

**Issue by SabeehY** [twobucks/react-gcaptcha#2]
Hi,
I am planning to implement this package in my project and it works great so far, only problem is that how do I reset the captcha if there is an error from the server side? 

Should I just access the global grecaptcha object and call reset, or is there a way this could be implemented in this package?

**Comment by dmason30** [comment]
@dinodsaurus

**Comment by dinodsaurus** [comment]
Thanks for the suggestion, I will implement this feature today ;)

**Comment by dinodsaurus** [comment]
ok, if you pass `reset={true}` to the component it will reset it. But the trick is that you need to do the book keeping of `reset`value. This is for now, but if you have any further questions or enhancement ideas just write them down :)
