### ISSUE TITLE
Update lib for new version of react [PropTypes warning]

### ISSUE THREAD

**Issue by prop-type-man** [twobucks/react-gcaptcha#4]
Could you update lib for new version of react?

> Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

Doc: https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes

Thanks.

**Comment by prop-type-man** [comment]
Could you rebuild dist ? minification version

**Comment by dinodsaurus** [comment]
Thanks a lot!
