### ISSUE TITLE
reset prop type

### ISSUE THREAD

**Issue by kubijo** [twobucks/react-gcaptcha#5]
Hi,
thanks for the component.

I have just a minor issue the type of the prop `reset`.
I think thath the semantics as it stands would work  better with number since when you want to trigger the reset more than once, you'd need to do double switch (`0 → 1`; `1 → 0 → 1`) 

Whereas you can just increment number.

**Comment by dinodsaurus** [comment]
thanks a lot for this suggestion, will work on this over the weekend ;)

**Comment by kubijo** [comment]
Thanks 👍

**Comment by dinodsaurus** [comment]
Its done, thanks once more for suggestions!
