### ISSUE TITLE
pass-throught className to rendered div

### ISSUE THREAD

**Issue by kubijo** [twobucks/react-gcaptcha#6]
It would be nice to be able to assign a className for styling/positioning sake in addition to the ID.
I didn't make a pull request as it's so little a change that it's faster for you to do it, but I'll make one next Monday if you want.

**Comment by dinodsaurus** [comment]
thanks a lot, makes sense 👍

**Comment by kubijo** [comment]
Hi. Have you got to those 2 changes or should I create a pull request?

**Comment by dinodsaurus** [comment]
This should be fixed in the new release 🥇
