### ISSUE TITLE
cannot do npm install on previous versions

### ISSUE THREAD

**Issue by trongphan** [twobucks/react-gcaptcha#8]
Hello,
I was trying to install a specific version (3.8.1) but I could not (not register on npm). Somehow the npm just automatically get the latest version (4.2.1). This version seems require the ReactJS 16, but it just works fine with ReactJS 15.x 

Any recommmends?

Thanks in advance,

**Comment by dinodsaurus** [comment]
hey @trongphan you just need to install it will `npm i react-gcaptcha@3.10.0`
